# Generated by Django 2.1.1 on 2018-12-07 11:27

import E_Vento.models
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.ImageField(default='media/no-img.png', upload_to=E_Vento.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarrinhoIngresso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qtd_ingresso', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('id_carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Carrinho')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='A', max_length=1)),
                ('data_compra', models.DateTimeField()),
                ('data_pagamento', models.DateTimeField()),
                ('id_carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Carrinho')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complemento', models.CharField(blank=True, max_length=200)),
                ('numero', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Eticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='[\\d]+')])),
                ('status', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.TextField()),
                ('qr_code', models.ImageField(default='media/no-img.png', upload_to='qr_code/')),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Compra')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='E', editable=False, max_length=1)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_hora_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio_venda', models.DateField(verbose_name='Inicio das vendas')),
                ('hora_inicio_venda', models.TimeField(verbose_name='Inicio das vendas')),
                ('data_fim_venda', models.DateField(verbose_name='Fim das vendas')),
                ('hora_fim_venda', models.TimeField(verbose_name='Fim das vendas')),
                ('id_categoria', models.ManyToManyField(to='E_Vento.Categoria', verbose_name='Categorias')),
                ('id_endereco', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Endereco', verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo de ingresso')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(regex='\\d\\d\\d\\d\\d\\d\\d\\d')])),
                ('id_bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Lote')),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('qtd_max', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_inicio_venda', models.DateField(verbose_name='Inicio das vendas')),
                ('hora_inicio_venda', models.TimeField(verbose_name='Inicio das vendas')),
                ('data_fim_venda', models.DateField(verbose_name='Fim das vendas')),
                ('hora_fim_venda', models.TimeField(verbose_name='Fim das vendas')),
                ('qtd_vendido', models.PositiveIntegerField(default=0)),
                ('id_ingresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Ingresso')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='[\\d]+')])),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=5)),
                ('id_endereco', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Endereco')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='id_promotor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eticket',
            name='id_ingresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Ingresso'),
        ),
        migrations.AddField(
            model_name='eticket',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Usuario'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='id_logradouro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Logradouro'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.FormaPagamento'),
        ),
        migrations.AddField(
            model_name='carrinhoingresso',
            name='id_lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Lote'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Usuario'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='ingressos',
            field=models.ManyToManyField(through='E_Vento.CarrinhoIngresso', to='E_Vento.Lote'),
        ),
        migrations.AddField(
            model_name='banner',
            name='id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Evento'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='id_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Vento.Municipio'),
        ),
    ]
