# Generated by Django 2.1.1 on 2018-09-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Vento', '0002_auto_20180921_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='nome',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
